### ISSUE TITLE
How to log to elasticsearch

### ISSUE THREAD

**Issue by svengo** [sematext/sematext-agent-docker#44]
Is there a way to log to a local elasticsearch container?

Thank You!

**Comment by otisg** [comment]
Please see https://sematext.com/docs/sematext-docker-agent/

**Comment by svengo** [comment]
Thank you, @otisg. I don't want to feed Elasticsearch logs into SDA, I want SDA to send logs to Elasticsearch. I didn't find the information in the docs, sorry :-(

**Comment by svengo** [comment]
I found the solution myself, excerpt from `docker-compose.yml`:

```` 
  sematext-agent:
    image: 'sematext/sematext-agent-docker:latest'
    environment:
      - LOGSENE_TOKEN=docker
      - LOGSENE_RECEIVER_URL=http://elasticsearch:9200
````

Closed.
