### ISSUE TITLE
kubernetes manifest error

### ISSUE THREAD

**Issue by Morriz** [sematext/sematext-agent-docker#8]
I believe the selector is obsolete, as I get this error:

```
error validating data: found invalid field selector for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

But if I remove it, the DaemonSet starts without errors, but I see nothing coming in...

**Comment by megastef** [comment]
Which Kubernetes version do you use? 
Did you enter SPM App Token and Logsene Token?

**Comment by megastef** [comment]
This issue might be relevant: https://github.com/kubernetes/kubernetes/issues/18130
https://github.com/kubernetes/kubernetes/issues/18130#issuecomment-163022690

Please note the apiVersion changed for 1.2 see comments in my DaemonSet definition: 

```
# Kubernetes 1.1.8
apiVersion: extensions/v1beta1
# Kubernetes 1.2
# apiVersion: v1
kind: DaemonSet
metadata:
  name: sematext-agent
spec:
  template:
    metadata:
      labels:
        app: sematext-agent
    spec:
      selector: {}
      dnsPolicy: "ClusterFirst"
      restartPolicy: "Always"
      containers:
      - name: sematext-agent
        image: sematext/sematext-agent-docker:latest
        imagePullPolicy: "Always"
        env:
        - name: SPM_TOKEN
          value: "REPLACE THIS WITH YOUR SPM TOKEN"
        - name: LOGSENE_TOKEN
          value: "REPLACE THIS WITH YOUR LOGSENE TOKEN"
        - name: KUBERNETES
          value: "1"
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
          - mountPath: /etc/localtime
            name: localtime
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: localtime
          hostPath:
            path: /etc/localtime
```

Create the daemonset with `kubectl create -f sematext-agent.yml --validate=false`
This worked at least with Kubernetes 1.1.8.
